#!/usr/bin/env sh
set -e

if [ "$1" = "completions" ] && [ "$2" = "fish" ]; then
  # print fish completions using the path of this file
  cat "$(dirname "$0")/completions.fish"
  exit 0
fi

if [ "$1" != "with" ]; then
  echo "Only 'with' is supported as the first argument."
  exit 1
fi

# remove first argument
shift

if [ "$#" -lt 1 ]; then
  echo "Please provide at least one branch or ref to merge with."
  exit 1
fi

# check for uncommitted changes
if [ -n "$(git status --porcelain)" ]; then
  echo "You have uncommitted changes. Please commit or stash them."
  exit 1
fi

# capture current branch
current_branch=$(git rev-parse --abbrev-ref HEAD)

# switch to detached HEAD state
git checkout --detach HEAD

# octopus merge with passed branches
git merge --no-ff -m "Ensemble commit of: $current_branch $*" "$@"