.\" git-ensemble.1 - quickly produce ensemble commits
.TH GIT-ENSEMBLE 1 "September 2025" "Git Manual"
.SH NAME
git-ensemble \- quickly produce ensemble commits
.SH USAGE
git ensemble with [refs...]
.SH DESCRIPTION
Produces a detached, octopus-merged commit of the current commit + the provide refs.
